### PR TITLE
Add Oracle JVMs (JDK and GraalVM) to the Index

### PR DESCRIPTION
**Pull request by carlosedp**
It generates the index and checks URLs for both JDK and GraalVM distributions.

Below is the index only for the changes:

```json
{
  "linux": {
    "amd64": {
      "graalvm-jdk@oracle": {
        "17": "https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_linux-x64_bin.tar.gz",
        "21": "https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz"
      },
      "jdk@oracle": {
        "17": "https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz",
        "21": "https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.tar.gz"
      }
    },
    "arm64": {
      "graalvm-jdk@oracle": {
        "17": "https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_linux-aarch64_bin.tar.gz",
        "21": "https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-aarch64_bin.tar.gz"
      },
      "jdk@oracle": {
        "17": "https://download.oracle.com/java/17/latest/jdk-17_linux-aarch64_bin.tar.gz",
        "21": "https://download.oracle.com/java/21/latest/jdk-21_linux-aarch64_bin.tar.gz"
      }
    }
  },
  "macos": {
    "amd64": {
      "graalvm-jdk@oracle": {
        "17": "https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_macos-x64_bin.tar.gz",
        "21": "https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_macos-x64_bin.tar.gz"
      },
      "jdk@oracle": {
        "17": "https://download.oracle.com/java/17/latest/jdk-17_macos-x64_bin.tar.gz",
        "21": "https://download.oracle.com/java/21/latest/jdk-21_macos-x64_bin.tar.gz"
      }
    },
    "arm64": {
      "graalvm-jdk@oracle": {
        "17": "https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_macos-aarch64_bin.tar.gz",
        "21": "https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_macos-aarch64_bin.tar.gz"
      },
      "jdk@oracle": {
        "17": "https://download.oracle.com/java/17/latest/jdk-17_macos-aarch64_bin.tar.gz",
        "21": "https://download.oracle.com/java/21/latest/jdk-21_macos-aarch64_bin.tar.gz"
      }
    }
  },
  "windows": {
    "amd64": {
      "graalvm-jdk@oracle": {
        "17": "https://download.oracle.com/graalvm/17/latest/graalvm-jdk-17_windows-x64_bin.zip",
        "21": "https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_windows-x64_bin.zip"
      },
      "jdk@oracle": {
        "17": "https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.zip",
        "21": "https://download.oracle.com/java/21/latest/jdk-21_windows-x64_bin.zip"
      }
    }
  }
}
```

### CODE REVIEW

**Comment by carlosedp** [comment]
@ckipp01 would you take a look at this?
Thanks!

**Comment by guizmaii** [comment]
+1

**Review by alexarchambault — APPROVED** [review]
Thanks @carlosedp!

**Comment by carlosedp** [comment]
Although this got merged a long time ago, I don't see these JVMs available in the index:

```
❯ cs java --available --update --ttl 0 | grep -i orac
Found existing global alias for "| grep". You should use: "G"
Checking https://github.com/coursier/jvm-index/raw/master/index.json
Checked https://github.com/coursier/jvm-index/raw/master/index.json
Downloading https://github.com/coursier/jvm-index/raw/master/index.json
Downloaded https://github.com/coursier/jvm-index/raw/master/index.json
❯ 
``` 

Anything else missing?

**Pull request merged**
